# Course:    CSCI 480
# Program:   Assignment 3
# Author:    Reid Wixom
# Z-number:  z1693990
# Date Due:  04/04/2017

hw3.exe: hw3.cpp
	g++ -std=c++11 -Wall -g hw3.cpp -o hw3.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm hw3.exe

