#
# PROGRAM:    Assignment 7
# PROGRAMMER: Reid Wixom
# LOGON ID:   z1693990
# DATE DUE:   4/2/16
#

assignment8.exe: assignment8.cc assignment8.h
	g++ -std=c++11 -Wall -g assignment8.cc -o assignment8.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm assignment8.exe
