#
# PROGRAM:    Assignment 7
# PROGRAMMER: Reid Wixom
# LOGON ID:   z1693990
# DATE DUE:   4/2/16
#

assignment9.exe: assignment9.cc assignment9.h
	g++ -std=c++11 -Wall -g assignment9.cc -o assignment9.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm assignment9.exe
