# Course:    CSCI 480
# Program:   Assignment 1
# Author:    Reid Wixom
# Z-number:  z1693990
# Date Due:  02/14/2017

hw1.exe: hw1.cpp Processor.cpp Processor.h
	g++ -std=c++11 -Wall -g hw1.cpp Processor.cpp -o hw1.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm hw1.exe
