# Course:    CSCI 480
# Program:   Assignment 2
# Author:    Reid Wixom
# Z-number:  z1693990
# Date Due:  03/02/2017

hw2.exe: hw2.cpp
	g++ -std=c++11 -Wall -g hw2.cpp -o hw2.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm hw2.exe

