#
# PROGRAM:    Assignment 7
# PROGRAMMER: Reid Wixom
# LOGON ID:   z1693990
# DATE DUE:   4/2/16
#

assignment7.exe: assignment7.cc
	g++ -std=c++11 -Wall -g assignment7.cc -o assignment7.exe

# Pseudo-target to remove object code and executable files
clean:
	-rm assignment7.exe
